### PR TITLE
Minor reorganization of project directory

### PR DESCRIPTION
**Pull request by alexpersian**
This PR simply performs some minor reorganization of the project. It creates a dedicated directory for holding the incident report files and updates the README to the new path. The non-reorg edit made was the change of New York State name to just New York.

### CODE REVIEW

**Comment by maxspencer** [comment]
I like this idea, but could we call the directory simply `reports`? Reason being it makes writing those links in markdown less intuitive and also because spaces can be annoying when doing stuff in the terminal?

**Comment by alexpersian** [comment]
@maxspencer good point on the space issue! Simply named it to copy the heading the links were under, so I'm happy to change 👍

**Comment by alexpersian** [comment]
If this is approved I will rebase on top of current `master` before merging since there will be constant conflicts from the directory change.

**Comment by 2020PB** [comment]
Going to merge a few more PRs in the queue real quick, then if you can rebase that'd be great.

**Comment by alexpersian** [comment]
Lots of merge activity 😅 this branch should be rebased and up-to-date now though and ready to merge @2020PB

**Comment by 2020PB** [comment]
Sorry Alex! I thought it'd take you a little bit to update so I merged a couple more minor edits after the last comment, my bad!

Thank you for this!

**Comment by alexpersian** [comment]
No worries! Thank you for maintaining this resource! ❤️

**Comment by ubershmekel** [comment]
These data layout changes broke https://2020policebrutality.netlify.app/

I just pushed out a fix. Please at-mention me if you want to do more so I can prepare.

FYI @2020PB @alexpersian

**Comment by alexpersian** [comment]
@ubershmekel sorry about that!! I didn’t realize that there was a site hooked into the directory structure when I made the change.

**Pull request merged**
