### PR TITLE
skynet data link

### PR DESCRIPTION
**Pull request by xloem**
add link to skynet archive.  ipfs still missing

### CODE REVIEW

**Comment by xloem** [comment]
Yes that is totally possible.  HTML files will render.

The archive was made by someone else in the skynet discord.  I just wanted to start a habit of linking to archives.

**Comment by xloem** [comment]
hey i am very taxed and scanning the discord.
```
@xloem @manasi 

https://skyportal.xyz/_ATQpqsu1tnEHkgDNk4jIzGMztXTSUka8FB7toGJkmOHag/index.html

I'd recommend just replacing each reports markdown file from your PR with these over including a single Skynet archive most of the reports "Links" section should have a new Skynet link attached to them: https://skyportal.xyz/LAAVFZ0zt505jhzIaNhfijbIJYhtoqA3crYdF1876FdyyQ 
```

**Comment by ubershmekel** [comment]
Thank you @xloem 

The bico page brought me to a "cool story bro" page which is empty: https://bico.media/Alabama.html

From the skyportal link at: https://skyportal.xyz/_ATQpqsu1tnEHkgDNk4jIzGMztXTSUka8FB7toGJkmOHag/index.html

I went to https://skyportal.xyz/_ATQpqsu1tnEHkgDNk4jIzGMztXTSUka8FB7toGJkmOHag/Alabama.html and got this error when I went to download a video from this link: https://siasky.net/AACyg4YcS3yZ_Ib4xdTarfSfQdBvZvaQPagpBFn8R-SFiw

```
{
  "message": "failed to fetch skylink: [unable to fetch base sector of skylink; timed out after 30s; project timed out; workers were unable to recover the data by sector root - all workers failed]"
}
```

Seems to me that this backup does not work yet. Am I using it wrong?

**Comment by xloem** [comment]
The siasky.net mirror used in the html file is struggling right now.  The video works fine from another mirror at https://siasky.dev/AACyg4YcS3yZ_Ib4xdTarfSfQdBvZvaQPagpBFn8R-SFiw (changed .net to .dev).  I linked this issue to the uploader in the chat channel.

**Comment by dostran4** [comment]
Any updates on this @xloem? Otherwise would like to close for inactivity.

**Comment by xloem** [comment]
I'm sorry; I'm not able to continue to contribute to this at this time.  If anybody has the capacity to continue this right now, ask in the sia skynet discord or just jump on it and make it work.  Otherwise, I guess closing makes some sense.

**Comment by dostran4** [comment]
Closing for inactivity.

**Pull request closed without merging**
