### PR TITLE
Assign ids where missing and fix id formatting

### PR DESCRIPTION
**Pull request by cwilper**
https://github.com/2020PB/police-brutality/issues/236

I didn't want to re-order and introduce conflicts, so I just picked unused ids where possible and cleaned up a few I noticed were problematic.

### CODE REVIEW

**Comment by rsarvar1a** [comment]
👑 @cwilper

**Comment by rsarvar1a** [comment]
Looks good. There's still quite a few overlapping #s in the IDs in [California](https://github.com/2020PB/police-brutality/tree/master/reports/California.md) and [New York](https://github.com/2020PB/police-brutality/tree/master/reports/New%20York.md). 

@cwilper (if you're down to help with more) and @emarcey we'll come up with a plan to correct them all later?

**Comment by haydenbspence** [comment]
How are we doing ids? should we put them in initially or is that more backend when its placed in the db?

**Comment by cwilper** [comment]
Absolutely down to help more on this. I see there was a one-time assignment of ids via this script: https://gist.github.com/ubershmekel/82d84c0834e90aeb8b1b46e42833fd03 but seems like going forward, the more this can be automated the better (and less error prone) it'll be. Meanwhile, I'm happy to submit patches as needed. 

There's some prior discussion here: https://github.com/2020PB/police-brutality/issues/236

**Comment by rsarvar1a** [comment]
We're having a discussion about what our ordering is going to be going forward. I'll let you know what our plans are whenever we come to a conclusion.

**Pull request merged**
