### PR TITLE
Remove incident CA-LosAngeles-24

### PR DESCRIPTION
**Pull request by ContributingThrowaway**
(See discussion in incident #681 )

### CODE REVIEW

**Comment by emarcey** [comment]
See discussion here on inclusion: https://github.com/2020PB/police-brutality/pull/459

**Comment by ContributingThrowaway** [comment]
Can you clarify what about the incident was felt to constitute police misconduct or brutality? (In particular, does anything evidenced by the links currently in the "links" section constitute police misconduct or brutality? If so, I’m not seeing it, and I think the description needs to be updated to clarify what the brutality or misconduct is here. If not, I suggest we remove the incident. The forms of brutality alleged in the Instagram posts linked in the original inclusion issue are better dealt with as their own separate incidents – the first post is already incident ca-losangeles-19; suggest we create a new incident for Porkie the Impaler and his overzealously-zip-tying colleagues from the second post.)

**Comment by emarcey** [comment]
1. Taking resources from a public transit system to bus peaceful protestors.
2. Did you read this account? https://www.instagram.com/p/CBBNXXkJs0a/
3. Masks removed and social distancing procedures not obeyed during a pandemic.

That adds up to misconduct and disregard for protestors' needs at least imo

**Comment by emarcey** [comment]
@rsarvar1a how do you feel about this one?

**Comment by rsarvar1a** [comment]
I think given the discussions we had regarding scope, surely this should be kept. It's a bit of an umbrella incident but I don't think it's necessarily a bad idea to leave it like this and encapsulate the accounts in this incident instead of making the account the incident and giving this as context

**Comment by ContributingThrowaway** [comment]
Thanks for the clarification. 

The instagram post (https://www.instagram.com/p/CBBNXXkJs0a/) seems to already be summarized (and linked) in incident ca-losangeles-19. It definitely constitutes misconduct (and brutality), and is being treated as such.

Metro alleges that the decision to shut down service had nothing to do with providing buses to the police; as far as I can tell, metro provided a tiny fraction of its total buses to the police (while stopping service for all of its buses), so the screwup here seems to be metro's, not LAPD's. None of the links provide evidence that I could see to the effect that LAPD's use of metro buses deprived the public of their use. That's not to say it didn't, but we don't seem to have evidence to that effect. (If we do have such evidence, please comment with it -- it would be very helpful.)

Neither the links nor the current description mention masks; do we have evidence that they were confiscated?

(I still feel very strongly that this incident description needs to be revised pretty radically. As it is now, people I've shown it to have given me that "huh???" look and asked how on earth anything alleged in the description or title constitutes police brutality. That gives ammunition to police apologists: reformer X will reference this repository; Fox News will report "Breaking -- [liberals/reformers/abolitionists/reformer X/whoever Fox wants to ridicule today] think being forced to ride a bus constitutes brutality." Unless someone else would like to make those revisions, I'll make them later today or tomorrow and submit a new pull request.)

**Comment by emarcey** [comment]
Oh I guess I missed that it was already covered in ca-losangeles-19. If that's the case, then I'm fine to remove

**Pull request merged**
