### PR TITLE
Update California.md

### PR DESCRIPTION
**Pull request by Ghostwaffles**
Adding May 30th incident to San Jose, community activist shot in groin.

### CODE REVIEW

**Comment by samgoldman** [comment]
I recommend adding this link from #440: https://twitter.com/DonovanFarley/status/1269701897377603584

**Comment by Ghostwaffles** [comment]
Edited with the twitter linke from #440 , but the one you linked is for an incident in Oregon a day or two ago

**Comment by samgoldman** [comment]
Thank you. This now closes #440.

**Comment by emarcey** [comment]
Hey sorry guys, I missed the comment on #440 so I think there might be a merge conflict now

**Comment by rsarvar1a** [comment]
@emarcey We can close this one, since it's a subset of the already-merged incident.

**Pull request closed without merging**
