### PR TITLE
Police Abuses of Power spreadsheet 40-80

### PR DESCRIPTION
**Pull request by emarcey**

### CODE REVIEW

**Comment by emarcey** [comment]
Fixed the las vegas title issue. It's all one commit, so might be a pain to split them out. If you're up for reviewing some of them, maybe you could mark which ones you've reviewed and someone else can review the rest?

**Comment by rsarvar1a** [comment]
Holy cow, nice work. I'm a bit tied up right now so this will unfortunately have to wait, but I'll go through and do a full review when I'm available.

**Comment by 00000100-00010100** [comment]
Good call, Florida and Nevada both look good

**Comment by rsarvar1a** [comment]
California's good, confirmed Florida and Nevada are fine as well.

**Comment by rsarvar1a** [comment]
+1 to Minnesota, New York, Ohio.

**Comment by rsarvar1a** [comment]
+1 to Texas, Washington.

**Pull request merged**
