### PR TITLE
[UPDATE] Added `zip-ties` tag to incidents (using text search only)

### PR DESCRIPTION
**Pull request by amardeshbd**
The `zip-ties` tag is added to incidents which mentioned this either in title or description.

- Tag is added as a part of effort mentioned in https://github.com/2020PB/police-brutality/issues/810
- The tag has been officially added in https://github.com/2020PB/police-brutality/pull/832

### CODE REVIEW

**Comment by emarcey** [comment]
This is a good first pass, but I'd go through again. I know at least ca-losangeles-32 and ca-santamonica-2 also have zip ties

**Comment by amardeshbd** [comment]
@emarcey Thanks for pointing out, did another pass, and updated PR.

**Comment by emarcey** [comment]
Are you doing a ctrl-F for "zip ties" or "zip-ties" or something. My one concern here is that police use zip ties for the vast, vast majority of protest-related arrests, because they can carry loads of them at a time. So I'm worried that by just searching on zip tie things, we're missing tons of incidents where zip ties are used

**Comment by amardeshbd** [comment]
Yes, that is correct, I have done a project-wide search for key terms like `zip`, `zip-ties`, `zip tied`, `tied` and so on.

Wanted to cover the most obvious case first. You can keep the issue open if anybody wants to go though each incident links and update the tags. Or, if you want this to happen in one go via that process, I am fine with that too. You can close this PR. Thanks

**Comment by emarcey** [comment]
No I think it's fine for a first pass, thanks!

**Pull request merged**
