### PR TITLE
DC: New incident

### LINKED ISSUE #851: Incident in Washington DC
---

## Location

Washington DC

## Date

July 7th

## Description

Protestor with megaphone is speaking to police. Police slowly surround him then seize him without warning. He panics and half a dozen cops force him to the ground.

## Links

https://twitter.com/JoshuaPotash/status/1280712378225696769
https://twitter.com/KuzyBeCackling/status/1280690030344888321

### PR DESCRIPTION
**Pull request by emarcey**
Closes #851

### CODE REVIEW

**Comment by ContributingThrowaway** [comment]
Worth figuring out what, if anything, he was eventually charged with? (It seems like the main problem here is police arresting him for no good reason, so it would be nice to know what their official reason was and whether it holds any water -- hint: looks like no.)

**Comment by emarcey** [comment]
https://twitter.com/occupyhstreet/status/1280967486964408322
https://twitter.com/DCMediaGroup/status/1281334939179462663

Looks like all charges were dropped

**Comment by emarcey** [comment]
@ContributingThrowaway updated accordingly!

**Comment by ubershmekel** [comment]
Good work describing and organizing the info here. Thank you!

**Pull request merged**
