### PR TITLE
Prepare master -> main switch

### PR DESCRIPTION
**Pull request by emarcey**

### CODE REVIEW

**Comment by emarcey** [comment]
#794 

@Murkantilism @ubershmekel 

This is set up so that the github actions will not be modified by the switch from master to main. I'll do the actual swap in a week.

**Review by Murkantilism — APPROVED** [review]
Ns if intentional but the target date coincides with the start of National Hispanic Heritage Month in the US! ✨🎉 =)

**Comment by emarcey** [comment]
It was not. But now I'm confused as to why it starts in the middle of the month 🤔

**Comment by Murkantilism** [comment]
>But now I'm confused as to why it starts in the middle of the month 🤔

Haha so was I until I read more about it [here](https://www.hispanicheritagemonth.gov/about/) late last week; 09/15 is significant because it is the anniversary of independence for Costa Rica, El Salvador, Guatemala, Honduras, and Nicaragua.

**Comment by ubershmekel** [comment]
Looks good to me :)

**Pull request merged**
