### PR TITLE
Added an extra link for protestor shot in head

### PR DESCRIPTION
**Pull request by Ge0rgeBr0ughton**
Just another piece of evidence.

### CODE REVIEW

**Comment by valkyrie9812** [comment]
new link looks good. But I can't access the first twitter link under that heading, the page says the content is restricted by the poster

**Comment by Ge0rgeBr0ughton** [comment]
> new link looks good. But I can't access the first twitter link under that heading, the page says the content is restricted by the poster

Could you merge this one and then I can make an edit separately from that to either add delete the twitter link or find another version of it?

**Comment by Ge0rgeBr0ughton** [comment]
In fact, I'll go delete the faulty link now and this edit can be merged. We have enough evidence for this one as is.

**Comment by BonkyMaroo** [comment]
I added the extra info here into the other fork (PR178).  Issue now resolved.

**Pull request closed without merging**
