### PR TITLE
Update New York.md

### PR DESCRIPTION
**Pull request by emarcey**

### CODE REVIEW

**Comment by emarcey** [comment]
Sorry for the chonky PR, just wanted to finally be done with the NYC Greg Doucette thread

**Comment by aaaaaron-ship-it** [comment]
Leaving a comment instead of a review, because I haven't left reviews before. I can also leave a review if you want.

I noticed 3 things:
-In "NYPD Officers hit and knock down a protestor and a journalist", I'm not sure if link 4 (line 565) is the same incident or not.
-In "Police arrest hospital employee acting as medic" (line 686), description could be a bit more clear. Instead of "laughed at them" I would say something like "laughed at detained protestors". It also might be worth adding that the detained protestors were confined to an 8x10 foot room.
-In "Couple arrested on their stoop for cheering protestors", the link goes to a twitter thread with the video mentioned in the description, and a picture showing the woman being arrested. It might be a good idea to mention this in the description and/or link that picture directly to indicate that there is photographic evidence of both people being arrested.

**Comment by rsarvar1a** [comment]
Great comments. I don't think anyone would mind if you wrote them out as reviews, especially since you can tie each comment to a location in the file.

I'll check it over once more when I'm done with IRL commitments.

**Comment by emarcey** [comment]
>-In "NYPD Officers hit and knock down a protestor and a journalist", I'm not sure if link 4 (line 565) is the same incident or not.
I'm reasonably confident it is, or it is at least in the same series of events. I was linking between the tagged reporters from the different videos who were communicating. I can broaden the description a little bit? Or just dump that link

@aaaaaron-ship-it

**Comment by aaaaaron-ship-it** [comment]
> I'm reasonably confident it is, or it is at least in the same series of events. I was linking between the tagged reporters from the different videos who were communicating. I can broaden the description a little bit? Or just dump that link

You probably know better than me but it seems like we can just add something to the description there. Seems like the main focus should still be on the first 3.

**Comment by emarcey** [comment]
> You probably know better than me but it seems like we can just add something to the description there.

Sure I'll update the description with something like "additional footage (link 4) from the reporters show police shoving protestors and journalists throughout the night"

**Comment by aaaaaron-ship-it** [comment]
Looks like there are duplicate ids in the new york file. We have 2 of:
id: ny-newyorkcity-32
id: ny-newyorkcity-41

It also doesn't look like I can be a reviewer for this one. I can see a link to "Add your review". Maybe because I'm not a requested reviewer?

**Comment by emarcey** [comment]
I think I fixed the IDs but maybe it's because you don't have write access? You're not showing up for me as a possible reviewer. I'll ping autobotter in the morning

**Comment by rsarvar1a** [comment]
Github online editor is truly awful but I believe all IDs are now unique.

**Pull request merged**
