### PR TITLE
Update Ohio.md

### PR DESCRIPTION
**Pull request by chusaur**

### CODE REVIEW

**Comment by ubershmekel** [comment]
Please see https://github.com/2020PB/police-brutality/blob/master/CONTRIBUTING.md#content-standards

> 2. Only add clear evidence of police brutality or abuse of power.

**Comment by chusaur** [comment]
So you want to wait until after the autopsy comes back after 8 weeks that says that her death was a direct cause of the police? Isn't that too late?

**Comment by ubershmekel** [comment]
@chusaur I'm asking for a third opinion.

**Comment by Freezman13** [comment]
@chusaur We are cataloging police brutality and misconduct instances. We have guidelines we try to follow. This doesn't seem to fall under our scope. The use of gas itself isn't enough to make it a brutality or misconduct issue.  There are plenty of legitimate reasons to use gas. While it's tragic that she died, there is no visual evidence presented that any misconduct was involved from the side of the police.

**Pull request closed without merging**
