### PR TITLE
Adding unique IDs to every event

### PR DESCRIPTION
**Pull request by ubershmekel**
Calling these IDS `pb-id` as in "police brutality id"

This will address https://github.com/2020PB/police-brutality/issues/236

### CODE REVIEW

**Comment by ubershmekel** [comment]
I used this python script to generate the ids for all the events: https://gist.github.com/ubershmekel/82d84c0834e90aeb8b1b46e42833fd03

I did not commit that script because we will never use it again.

There are a few things to review here:

* The id format is `pb-id: {state_abbrev}-{city_abbrev}-{city_index}`, we can change that if something better makes more sense. Some were asking for UUIDs but I think these need to be short because they will show up as parts of URLs in sites that people build around this dataset. The downside of using the index in the end is that people might be attracted to change the index when or if they re-order the page contents. We must make sure that doesn't happen. If that's a real concern we could rename the field to be `permanent-id: {state_abbrev}-{city_abbrev}-{city_index}` or `dontchange-id: {state_abbrev}-{city_abbrev}-{city_index}`
* The place I put the `id` in is actually a far-reaching change. It's a format for more data we want to fit into the markdown files. For example see the following idea to include a `tags` field.:

```
## Atlanta

### Officer shoves a woman with his bike | May 30th

Police officer is seen shoving two women off onto the side with his bicycle.

pb-id: ga-atlanta-1

tags: bicycle,shoving,female-victim

**Links**

* https://twitter.com/ava/status/1266797973834395648?s=20
```

Similarly we could add a locations field.

**Comment by MicahRCM** [comment]
This is awesome! Regarding #83 do you think it might be more prudent to handle incident ids solely in the JSON output you created as opposed requiring contributors to add this in the .md files? It will further complicate submissions (I'm assuming there are going to be a lot of erroneous errors or duplicate ids). 

Why not generate the ids in the JSON file one time, now, and when new submissions are added, iterate over our object but skip anything that currently has an id assigned.

Pseudo:

```
for (let i = 0; i < states.length; i++) {
    for (let j = 0; j < states[i].cities.length; j++) {
        for (let k = 0; k < states[i].cities[j].reports.length; k++) {
        	// Might want to add a sort to push all reports with a pb_id to the front of the array before beginning iteration
        	// so as to have a consistent enumeration pattern
            if (!states[i].cities[j].reports[k].pb_id) {
                states[i].cities[j].reports[k].pb_id = states[i].abbreviation + "_" + cities[j] + "_" + k
            }
            // Expected output example: CA_Sacramento_1
        }
    }
}
```

**Comment by ubershmekel** [comment]
@MicahRCM what would be the source of truth? Let's say somebody changes the name of the event in the markdown, how would we know to update that in the json? If I understood you correctly - we'd need to have the id present in the markdown as well for that.

Right now the source of truth is the markdown because that was the easiest way for us to set up a system where practically anyone can contribute, and we have full, public, audit history.

Perhaps to clarify how the current pipeline works - every push to `master` triggers a build that takes all the state `.md` files, parses them, and pushes them into the other `json`, `csv`, and `md` files.

**Comment by 00000100-00010100** [comment]
This sounds like a good solution to me.

**Comment by MicahRCM** [comment]
@ubershmekel Great point regarding the source of truth... I can think of a couple of complex ways we can have the source of truth outside of the MD file! That being said (overly complex) an extra line of data per entry and a slight increase in collaborator diligence is a small price to pay. Thanks for the hard work!

**Comment by ubershmekel** [comment]
Thank you @MicahRCM @00000100-00010100 @maxspencer 

Seems we agree on most things here. I'll re-run the script.

I'll make it `id` instead of `pbid` but I still won't commit this to the repo because it will be dead code that no one will ever use again and I don't want to overwhelm new contributors with more code than what this repo actively uses. E.g. I think the `downloader` tool could also be on its own repo.

**Comment by maxspencer** [comment]
@00000100-00010100 @ubershmekel 👍

**Comment by maxspencer** [comment]
@ubershmekel one minor point to clarify: by `{city_index}` we actually mean `{state_index}`, e.g. for [Arkansas](https://github.com/2020PB/police-brutality/blob/master/reports/Arkansas.md) there are two reports: `ar-bentonville-1` and `ar-littlerock-2` rather than `ar-bentonville-1` and `ar-littlerock-1`.

**Comment by ubershmekel** [comment]
@maxspencer sorry. I'm not sure how I missed that.

**Pull request merged**
