### PR TITLE
Update New York.md

### PR DESCRIPTION
**Pull request by jackschottman**
Buffalo > Police shove elderly man. 
Adding details about cops involved and more source links

### CODE REVIEW

**Comment by ubershmekel** [comment]
Our policy is to avoid doxxing cops and those involved unless it's linking to a news article with officially recognized information. If you'd like to give us doxxing information - message the mods of the reddit and we'll file that information which we can provide privately to relevant parties.

**Comment by jackschottman** [comment]
Oh gotcha, makes sense!

**Comment by jackschottman** [comment]
I wasn't able to find that anywhere in the instructions/readme. I might have missed it but if not, would you be interested in a PR that adds that policy to the "content guidelines" or "how to contribute" page?

**Comment by ubershmekel** [comment]
@jackschottman yes please do.

**Pull request merged**
