### PR TITLE
Add incident AL-Birmingham-2

### PR DESCRIPTION
**Pull request by ContributingThrowaway**
Added incident AL-Birmingham-2, the arrest of The Root journalist Michael Harriot. There is a slight discrepancy between the coverage of the incident in AL.com and the way Harriot describes it. (See description. There is video, but I can't make out exactly what was said from it. My working theory is that Harriot (a respected writer at a major publication) is probably telling the truth and AL.com (a smaller publication that reads rather like a school newspaper) probably screwed up.)

### CODE REVIEW

**Comment by emarcey** [comment]
I think this could be waaaaaay condensed

**Comment by emarcey** [comment]
I think this could be way condensed

**Comment by ContributingThrowaway** [comment]
The typo is present in the original AL.com story. (See prior comment about AL.com reading like a school newspaper.) The information that Harriot said there was no way to contact his media outlet seems to come from a police officer, by way of AL.com, so I don't necessarily put too much stock in it.

**Comment by emarcey** [comment]
Ah I see. Maybe throw a \[_sic_\] in there so we don't get a bunch of spelling error reports.

**Comment by emarcey** [comment]
This looks great! Thanks for your attention to detail on all of these PRs!

**Pull request merged**
