### PR TITLE
Update Louisiana.md

### PR DESCRIPTION
**Pull request by emarcey**
Adding additional image & note on woman struck by rubber bullet.

### CODE REVIEW

**Comment by valkyrie9812** [comment]
How do you know that happened at that exact incident? I don't see anyone talking about it in the comments under it.

**Comment by emarcey** [comment]
Clicking on the linked tweet, the image is a direct reply to footage of police firing on the bridge.

**Comment by emarcey** [comment]
And the woman appears to be leaning against a concrete median of the type seen in the video

**Comment by emarcey** [comment]
I do need to update: a later report by the woman's daughter says it was a tear gas canister that struck the woman

**Pull request merged**
